export const data = [
    {
        id: 1,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Shirin Asqarova",
        fakultet: "Fiz-Mat",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        maxScore: 10,
        status: true,
        isRated: true,

        gradingTime: true,
    },
    {
        id: 2,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Shirin Asqarova",
        fakultet: "Fiz-Mat",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: false,
        maxScore: 10,
        gradingTime: false,
    },
    {
        id: 3,
        rasm: "https://cdn.worldvectorlogo.com/logos/4x4-1.svg",
        name: "Azimjon Shukur",
        fakultet: "Fiz-Mat",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: true,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 4,
        rasm: "",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: false,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 5,
        rasm: "https://cdn.worldvectorlogo.com/logos/4x4-1.svg",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: true,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 6,
        rasm: "",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: false,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 7,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 8,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 9,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 10,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 11,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 12,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
];

export const dataTopKorTable = [
    {
        id: 1,
        title: "Matematika Darslari IJIOJ ijiojoi IJIJIJ iji вoaj oi",
        kategorya: "Majburiy",
        maxBal: "10",
        start: "01-02-2024",
        finish: "02-02-2024",
    },
    {
        id: 2,
        title: "Ingliz Tili",
        kategorya: "O'z tashabbusi",
        maxBal: "6",
        start: "03-02-2024",
        finish: "04-02-2024",
    },
    {
        id: 3,
        title: "Fizika",
        kategorya: "Qo'shimcha",
        maxBal: "3",
        start: "05-02-2024",
        finish: "06-02-2024",
    },
];
